### ISSUE TITLE
ValueCounter is always reseting max value - it should not do so for getStatistics(false)

### ISSUE THREAD

**Issue by deffer** [avaje-metric/avaje-metric-core#3]
In the ValueCounter.getStatistics(reset) in the else block (so when reset==false) it says 

return new DefaultValueStatistics(startTime.get(), count.sum(), total.sum(), max.maxThenReset());

Is that intentional (max value reset)?

**Comment by rbygrave** [comment]
Hi, no that is a bug in that it should really be max.max() .... rather than max.maxThenReset().

**Comment by rbygrave** [comment]
Fixed in master, closing (will release shortly)
